#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use AfolabiAbass\App\SentimentCommand;

$app = new Application();
$app->add(new SentimentCommand());
$app->run();
